### ISSUE TITLE
Awesome Job!!!

### ISSUE THREAD

**Issue by dulibubai** [daixiangzi/Awesome-Token-Compress#1]
An excellent example for me to learn.

**Comment by daixiangzi** [comment]
Thank you for your attention.

**Comment by Luo-Z13** [comment]
> Thank you for your attention.

Hello, I come across an article titled IVTP: Instruction-guided Visual Token Pruning for Large Vision-Language Models (https://www.ecva.net/papers/eccv_2024/papers_ECCV/papers/02577.pdf)

**Comment by daixiangzi** [comment]
> > Thank you for your attention.
> 
> Hello, I come across an article titled IVTP: Instruction-guided Visual Token Pruning for Large Vision-Language Models (https://www.ecva.net/papers/eccv_2024/papers_ECCV/papers/02577.pdf)

ok,I'll check it out later
