### ISSUE TITLE
ViT compress

### ISSUE THREAD

**Issue by ChenhongyiYang** [daixiangzi/Awesome-Token-Compress#3]
Hi, thank you for your great work. Could you please include our ICLR 2023 paper on ViT token compression? [https://openreview.net/forum?id=IowKt5rYWsK](https://openreview.net/forum?id=IowKt5rYWsK)

**Comment by daixiangzi** [comment]
> Hi, thank you for your great work. Could you please include our ICLR 2023 paper on ViT token compression? https://openreview.net/forum?id=IowKt5rYWsK

Excellent work, but the topic doesn't seem to be that specific to token compression....

**Comment by ChenhongyiYang** [comment]
thanks
